/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConexionBD;
import Modelo.Ubicacion;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Darwin Criollo
 */
public class datosIngresados extends javax.swing.JFrame {
ConexionBD conexion = new ConexionBD();
    /**
     * Creates new form datosIngresados
     */
    public datosIngresados() {
        initComponents();
        
    }

    /**s
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "IID", "Nombre", "Edad", "Estrato"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("generar datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "ciudad", "barrio", "departamento", "descripcion"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(140, 140, 140)
                .addComponent(Buscar)
                .addGap(347, 347, 347))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Buscar))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Crear una instancia de la clase ConexionBD
    

    // Obtener el modelo de datos de la tabla usuarios
    DefaultTableModel modeloUsuarios = conexion.obtenerDatosUsuarios();

    // Asignar el modelo a jTable1
    jTable1.setModel(modeloUsuarios);

    // Obtener el modelo de datos de la tabla ubicación
    DefaultTableModel modeloUbicacion = conexion.obtenerDatosUbicacion();

    // Asignar el modelo a jTable2
    jTable2.setModel(modeloUbicacion);

    // Obtener el ID del usuario seleccionado en jTable1
    int filaSeleccionada = jTable1.getSelectedRow();

    if (filaSeleccionada != -1) {
        int idUsuarioSeleccionado = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());

        // Obtener la ubicación del usuario seleccionado
        // Puedes acceder a los datos de ubicación a través de jTable2
        // No es necesario realizar una consulta adicional en este punto
    }

    // Cerrar la conexión cuando ya no se necesite
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // Mostrar un cuadro de diálogo de entrada para ingresar el código de ubicación
    String codigoU = JOptionPane.showInputDialog(this, "Ingrese el código de ubicación:", "Buscar Ubicación", JOptionPane.QUESTION_MESSAGE);

    // Verificar si se ingresó un código de ubicación
    if (codigoU != null && !codigoU.isEmpty()) {
        // Obtener el modelo de la tabla de ubicación
        DefaultTableModel modeloUbicacion = (DefaultTableModel) jTable2.getModel();

        // Eliminar todas las filas actuales de la tabla
        modeloUbicacion.setRowCount(0);

        // Recorrer el modelo original de la tabla y agregar solo las filas que coincidan con el código de ubicación
        DefaultTableModel modeloOriginal = conexion.obtenerDatosUbicacion();
        for (int i = 0; i < modeloOriginal.getRowCount(); i++) {
            String codigoUbicacion = modeloOriginal.getValueAt(i, 4).toString(); // Suponiendo que el código de ubicación está en la última columna
            if (codigoUbicacion.equals(codigoU)) {
                modeloUbicacion.addRow(new Object[]{
                    modeloOriginal.getValueAt(i, 0), // Código
                    modeloOriginal.getValueAt(i, 1), // Ciudad
                    modeloOriginal.getValueAt(i, 2), // Barrio
                    modeloOriginal.getValueAt(i, 3), // Departamento
                    modeloOriginal.getValueAt(i, 4)  // Descripción
                });
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Debe ingresar un código de ubicación válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datosIngresados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
        
        
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

}
